const KEY='puravigal_pos_demo_v3';
const seed={business:{name:'Puravigal Store',type:'Grocery / Provision Store',country:'India',currency:'INR'},products:[
{id:1,name:'Aashirvaad Atta 5kg',sku:'ATTA-005',category:'Grocery',price:285,cost:248,stock:18,min:5},
{id:2,name:'India Gate Basmati 5kg',sku:'RICE-005',category:'Grocery',price:540,cost:475,stock:12,min:4},
{id:3,name:'Surf Excel 1kg',sku:'SURF-001',category:'Home Care',price:185,cost:154,stock:7,min:5},
{id:4,name:'Nescafe Classic 100g',sku:'NES-100',category:'Beverages',price:310,cost:260,stock:3,min:5},
{id:5,name:'Tata Salt 1kg',sku:'SALT-001',category:'Grocery',price:30,cost:24,stock:42,min:10}],
customers:[{id:1,name:'Walk-in Customer',phone:'',outstanding:0},{id:2,name:'Rahman Stores',phone:'9876543210',outstanding:1850}],
suppliers:[{id:1,name:'ABC Wholesale',phone:'9000000001',outstanding:12400}],
sales:[{id:1001,invoice:'INV-1001',date:'Today 10:42',customer:'Walk-in Customer',total:1250,payment:'UPI',status:'Paid'},{id:1002,invoice:'INV-1002',date:'Today 11:18',customer:'Rahman Stores',total:3480,payment:'Cash',status:'Paid'}],
purchases:[{id:501,ref:'PUR-501',date:'Today 09:20',supplier:'ABC Wholesale',total:8200,status:'Received'}],
team:[{id:1,name:'Owner',email:'owner@puravigal.local',role:'Owner/Admin',status:'Active'},{id:2,name:'Cashier',email:'cashier@puravigal.local',role:'Cashier',status:'Active'}],
settings:{tax:true,whatsapp:true,lowStock:true}};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||seed,cart=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const pages={dashboard:'Dashboard',billing:'Billing',products:'Products',inventory:'Inventory',purchases:'Purchases',customers:'Customers',suppliers:'Suppliers',reports:'Reports',team:'Team & roles',settings:'Settings'};
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:state.business.currency||'INR'}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function toast(message){const d=document.createElement('div');d.className='toast';d.textContent=message;document.body.append(d);setTimeout(()=>d.remove(),2200)}
function closeModal(){$('#modal').classList.add('hidden')}
function modal(html){$('#modalCard').innerHTML=html;$('#modal').classList.remove('hidden')}
function head(title,sub,actions){return '<div class="head"><div><h1>'+title+'</h1><p>'+sub+'</p></div><div class="actions">'+(actions||'')+'</div></div>'}
function dashboard(){
const sales=state.sales.reduce((a,b)=>a+b.total,0),low=state.products.filter(p=>p.stock<=p.min).length,out=state.customers.reduce((a,b)=>a+b.outstanding,0);
return head('Good evening, Owner','Business snapshot for today','<button class="btn primary" data-go="billing">+ New bill</button>')+
'<div class="stats"><div class="stat"><small>Today sales</small><strong>'+money(sales)+'</strong><span class="trend up">↑ 12.8% vs yesterday</span></div><div class="stat"><small>Bills today</small><strong>'+state.sales.length+'</strong><span class="trend up">Healthy activity</span></div><div class="stat"><small>Low stock</small><strong>'+low+'</strong><span class="trend '+(low?'down':'up')+'">'+(low?'Needs attention':'All good')+'</span></div><div class="stat"><small>Outstanding</small><strong>'+money(out)+'</strong><span class="trend">Customer balances</span></div></div>'+
'<div class="layout2"><div class="card"><div class="cardhead"><h3>Sales trend</h3><span class="muted">Last 7 days</span></div><div class="chart">'+[45,58,52,72,66,85,96].map((v,i)=>'<div class="col"><i style="height:'+v+'%"></i><span>'+['Mon','Tue','Wed','Thu','Fri','Sat','Today'][i]+'</span></div>').join('')+'</div></div>'+
'<div class="card"><div class="cardhead"><h3>Low stock</h3><span class="muted">'+low+' items</span></div><div class="list">'+state.products.filter(p=>p.stock<=p.min).map(p=>'<div class="row"><span class="avatar">'+esc(p.name[0])+'</span><div class="grow"><b>'+esc(p.name)+'</b><small>'+p.sku+'</small></div><span class="badge red">'+p.stock+' left</span></div>').join('')+'</div></div></div>'+
'<div class="card" style="margin-top:13px">'+salesTable()+'</div>'
}
function salesTable(){return '<div class="cardhead"><h3>Recent sales</h3><button class="btn" data-go="reports">View all</button></div><div class="tablewrap"><table class="table"><thead><tr><th>Invoice</th><th>Time</th><th>Customer</th><th>Payment</th><th>Total</th><th>Status</th></tr></thead><tbody>'+state.sales.slice().reverse().map(s=>'<tr><td><b>'+s.invoice+'</b></td><td>'+s.date+'</td><td>'+esc(s.customer)+'</td><td>'+s.payment+'</td><td><b>'+money(s.total)+'</b></td><td><span class="badge green">'+s.status+'</span></td></tr>').join('')+'</tbody></table></div>'}
function billing(){
return head('Billing','Fast checkout for daily sales','<button class="btn" id="scan">⌗ Scan barcode</button>')+
'<div class="billing"><div class="card"><div class="toolbar"><input id="bq" class="input search" placeholder="Search product or SKU"><select id="bc" class="select"><option>All categories</option>'+[...new Set(state.products.map(p=>p.category))].map(c=>'<option>'+esc(c)+'</option>').join('')+'</select></div><div id="tiles" class="tiles">'+tiles(state.products)+'</div></div>'+
'<div class="card"><div class="cardhead"><h3>Current bill</h3><span id="count" class="badge">0 items</span></div><div id="items" class="billitems">'+cartHtml()+'</div><div class="summary"><div class="sum"><span>Subtotal</span><b id="sub">₹0.00</b></div><div class="sum"><span>Tax</span><b id="tax">₹0.00</b></div><div class="sum total"><span>Total</span><span id="total">₹0.00</span></div><div class="paygrid"><button class="pay active" data-pay="Cash">Cash</button><button class="pay" data-pay="UPI">UPI</button><button class="pay" data-pay="Card">Card</button></div><button id="finish" class="btn primary" style="width:100%;margin-top:9px">Complete bill</button></div></div></div>'
}
function tiles(products){return products.map(p=>'<button class="tile" data-add="'+p.id+'"><span class="badge">'+esc(p.category)+'</span><b>'+esc(p.name)+'</b><small>'+p.sku+' · '+money(p.price)+'</small></button>').join('')||'<div class="empty">No products found.</div>'}
function cartHtml(){return cart.length?cart.map(i=>{const p=state.products.find(x=>x.id===i.id);return '<div class="billrow"><div><b>'+esc(p.name)+'</b><small>'+money(p.price)+' each</small></div><input class="input qty" type="number" min="1" value="'+i.qty+'" data-qty="'+i.id+'"><b>'+money(p.price*i.qty)+'</b><button class="btn" data-remove="'+i.id+'">×</button></div>'}).join(''):'<div class="empty">Add products to start a bill.</div>'}
function cartRender(){if(!$('#items'))return;$('#items').innerHTML=cartHtml();$('#count').textContent=cart.reduce((a,b)=>a+b.qty,0)+' items';const sub=cart.reduce((a,i)=>a+state.products.find(p=>p.id===i.id).price*i.qty,0),tax=state.settings.tax?sub*.05:0;$('#sub').textContent=money(sub);$('#tax').textContent=money(tax);$('#total').textContent=money(sub+tax)}
function finishBill(){if(!cart.length)return toast('Add at least one product');const pay=$('.pay.active')?.dataset.pay||'Cash',sub=cart.reduce((a,i)=>a+state.products.find(p=>p.id===i.id).price*i.qty,0),total=sub+(state.settings.tax?sub*.05:0);cart.forEach(i=>{const p=state.products.find(x=>x.id===i.id);p.stock=Math.max(0,p.stock-i.qty)});state.sales.push({id:Date.now(),invoice:'INV-'+(1000+state.sales.length+1),date:'Just now',customer:'Walk-in Customer',total,payment:pay,status:'Paid'});save();cart=[];toast('Bill completed');go('dashboard')}
function products(){return head('Products','Master catalogue with pricing and stock','<button class="btn" id="export-products">Export</button><button class="btn primary" id="add-product">+ Add product</button>')+'<div class="toolbar"><input id="pq" class="input search" placeholder="Search product, SKU or category"><select id="pf" class="select"><option>All</option><option>Low stock</option><option>Out of stock</option></select></div><div class="tablewrap"><table class="table"><thead><tr><th>Product</th><th>SKU</th><th>Category</th><th>Cost</th><th>Selling</th><th>Stock</th><th>Status</th><th></th></tr></thead><tbody id="prows"></tbody></table></div>'}
function productRows(){const q=($('#pq')?.value||'').toLowerCase(),f=$('#pf')?.value||'All';$('#prows').innerHTML=state.products.filter(p=>(!q||[p.name,p.sku,p.category].join(' ').toLowerCase().includes(q))&&(f==='All'||(f==='Low stock'&&p.stock<=p.min&&p.stock>0)||(f==='Out of stock'&&p.stock===0))).map(p=>'<tr><td><b>'+esc(p.name)+'</b></td><td>'+p.sku+'</td><td>'+p.category+'</td><td>'+money(p.cost)+'</td><td>'+money(p.price)+'</td><td>'+p.stock+'</td><td><span class="badge '+(p.stock===0?'red':p.stock<=p.min?'amber':'green')+'">'+(p.stock===0?'Out':p.stock<=p.min?'Low':'Healthy')+'</span></td><td><button class="btn" data-edit="'+p.id+'">Edit</button></td></tr>').join('')}
function productForm(id){const p=state.products.find(x=>x.id===id)||{name:'',sku:'',category:'Grocery',cost:0,price:0,stock:0,min:0};modal('<div class="modalhead"><h2>'+(id?'Edit':'Add')+' product</h2><button class="close" id="modal-close">×</button></div><form id="pfm" class="formgrid"><div class="field full"><label>Product name</label><input name="name" required value="'+esc(p.name)+'"></div><div class="field"><label>SKU / Barcode</label><input name="sku" required value="'+esc(p.sku)+'"></div><div class="field"><label>Category</label><input name="category" value="'+esc(p.category)+'"></div><div class="field"><label>Purchase price</label><input name="cost" type="number" min="0" step=".01" value="'+p.cost+'"></div><div class="field"><label>Selling price</label><input name="price" type="number" min="0" step=".01" value="'+p.price+'"></div><div class="field"><label>Current stock</label><input name="stock" type="number" min="0" value="'+p.stock+'"></div><div class="field"><label>Minimum stock</label><input name="min" type="number" min="0" value="'+p.min+'"></div><div class="field full"><button class="btn primary">Save product</button></div></form>');$('#modal-close').onclick=closeModal;$('#pfm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),obj={name:d.name,sku:d.sku,category:d.category,cost:+d.cost,price:+d.price,stock:+d.stock,min:+d.min};if(id)Object.assign(p,obj);else state.products.push({id:Date.now(),...obj});save();closeModal();go('products');toast('Product saved')}}
function inventory(){const v=state.products.reduce((a,p)=>a+p.cost*p.stock,0),low=state.products.filter(p=>p.stock<=p.min&&p.stock>0).length,out=state.products.filter(p=>p.stock===0).length;return head('Inventory','Stock position, value and reorder visibility','<button class="btn" id="adjust">Adjust stock</button>')+'<div class="stats"><div class="stat"><small>Stock value</small><strong>'+money(v)+'</strong><span class="trend">At purchase cost</span></div><div class="stat"><small>Total units</small><strong>'+state.products.reduce((a,p)=>a+p.stock,0)+'</strong><span class="trend">All products</span></div><div class="stat"><small>Low stock</small><strong>'+low+'</strong><span class="trend down">Reorder soon</span></div><div class="stat"><small>Out of stock</small><strong>'+out+'</strong><span class="trend down">Immediate action</span></div></div><div class="card" style="margin-top:13px">'+stockTable()+'</div>'}
function stockTable(){return '<div class="cardhead"><h3>Current stock</h3><span class="muted">Inventory foundation</span></div><div class="tablewrap"><table class="table"><thead><tr><th>Product</th><th>Category</th><th>On hand</th><th>Minimum</th><th>Unit cost</th><th>Stock value</th><th>Status</th></tr></thead><tbody>'+state.products.map(p=>'<tr><td><b>'+esc(p.name)+'</b></td><td>'+p.category+'</td><td>'+p.stock+'</td><td>'+p.min+'</td><td>'+money(p.cost)+'</td><td>'+money(p.cost*p.stock)+'</td><td><span class="badge '+(p.stock===0?'red':p.stock<=p.min?'amber':'green')+'">'+(p.stock===0?'Out':p.stock<=p.min?'Low':'Healthy')+'</span></td></tr>').join('')+'</tbody></table></div>'}
function generic(type,title,sub){const data=state[type];const rows=type==='purchases'?data.map(x=>'<tr><td><b>'+x.ref+'</b></td><td>'+x.date+'</td><td>'+esc(x.supplier)+'</td><td>'+money(x.total)+'</td><td><span class="badge green">'+x.status+'</span></td><td><button class="btn">View</button></td></tr>').join(''):data.map(x=>'<tr><td><b>'+esc(x.name)+'</b></td><td>'+esc(x.phone||'—')+'</td><td>'+money(x.outstanding)+'</td><td><span class="badge green">Active</span></td><td><button class="btn">View</button></td></tr>').join('');const cols=type==='purchases'?'<th>Reference</th><th>Date</th><th>Supplier</th><th>Total</th><th>Status</th><th></th>':'<th>Name</th><th>Phone</th><th>Outstanding</th><th>Status</th><th></th>';return head(title,sub,'<button class="btn primary" id="quick-add">+ Add</button>')+'<div class="tablewrap"><table class="table"><thead><tr>'+cols+'</tr></thead><tbody>'+rows+'</tbody></table></div>'}
function quickForm(type){const label=type==='customers'?'Customer':type==='suppliers'?'Supplier':'Purchase';modal('<div class="modalhead"><h2>Add '+label+'</h2><button class="close" id="modal-close">×</button></div><form id="qf" class="formgrid"><div class="field"><label>Name</label><input name="name" required></div><div class="field"><label>Phone</label><input name="phone"></div><div class="field"><label>Opening amount</label><input name="amount" type="number" min="0" value="0"></div><div class="field full"><button class="btn primary">Save</button></div></form>');$('#modal-close').onclick=closeModal;$('#qf').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(type==='customers'||type==='suppliers')state[type].push({id:Date.now(),name:d.name,phone:d.phone,outstanding:+d.amount});else state.purchases.unshift({id:Date.now(),ref:'PUR-'+(500+state.purchases.length+1),date:'Just now',supplier:d.name,total:+d.amount,status:'Received'});save();closeModal();go(type);toast(label+' saved')}}
function reports(){const s=state.sales.reduce((a,b)=>a+b.total,0),p=state.purchases.reduce((a,b)=>a+b.total,0);return head('Reports & analytics','Sales, purchases, payments and inventory visibility','<button class="btn" id="export-sales">Export CSV</button>')+'<div class="stats"><div class="stat"><small>Gross sales</small><strong>'+money(s)+'</strong><span class="trend up">Current period</span></div><div class="stat"><small>Purchases</small><strong>'+money(p)+'</strong><span class="trend">Recorded purchases</span></div><div class="stat"><small>Average bill</small><strong>'+money(state.sales.length?s/state.sales.length:0)+'</strong><span class="trend">Per invoice</span></div><div class="stat"><small>Refunds</small><strong>'+money(0)+'</strong><span class="trend">No refunds recorded</span></div></div><div class="card" style="margin-top:13px">'+salesTable()+'</div>'}
function team(){return head('Team & roles','Owner and staff access control','<button class="btn primary" id="invite">+ Invite staff</button>')+'<div class="tablewrap"><table class="table"><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Status</th><th></th></tr></thead><tbody>'+state.team.map(u=>'<tr><td><b>'+esc(u.name)+'</b></td><td>'+esc(u.email)+'</td><td><span class="badge">'+esc(u.role)+'</span></td><td><span class="badge green">'+u.status+'</span></td><td><button class="btn" data-perm="'+u.id+'">Permissions</button></td></tr>').join('')+'</tbody></table></div>'}
function settings(){return head('Settings','Business, regional, invoice and operational controls','<button class="btn" id="edit-business">Edit business</button>')+'<div class="layout2"><div class="card"><div class="cardhead"><h3>Business profile</h3></div><div class="setting"><b>Business name</b><p>'+esc(state.business.name)+'</p></div><div class="setting"><b>Business type</b><p>'+esc(state.business.type)+'</p></div><div class="setting"><b>Country / currency</b><p>'+esc(state.business.country)+' · '+state.business.currency+'</p></div></div><div class="card"><div class="cardhead"><h3>Operational controls</h3></div>'+setting('Tax calculation','Apply configured tax rules.','tax')+setting('WhatsApp delivery','Invoice delivery integration.','whatsapp')+setting('Low-stock alerts','Flag products at or below minimum.','lowStock')+'</div></div><div class="card" style="margin-top:13px"><div class="cardhead"><h3>Data portability</h3><span class="muted">Export first-class</span></div><div class="actions"><button class="btn" id="export-products">Export products</button><button class="btn" id="export-sales">Export sales</button><button class="btn" id="import-demo">Import data</button><button class="btn" id="backup">Backup now</button></div></div>'}
function setting(title,desc,key){return '<div class="setting"><div><b>'+title+'</b><p>'+desc+'</p></div><button class="switch '+(state.settings[key]?'on':'')+'" data-setting="'+key+'"><i></i></button></div>'}
function businessForm(){modal('<div class="modalhead"><h2>Business profile</h2><button class="close" id="modal-close">×</button></div><form id="bf" class="formgrid"><div class="field full"><label>Business name</label><input name="name" required value="'+esc(state.business.name)+'"></div><div class="field"><label>Business type</label><input name="type" value="'+esc(state.business.type)+'"></div><div class="field"><label>Country</label><input name="country" value="'+esc(state.business.country)+'"></div><div class="field"><label>Currency</label><select name="currency"><option>INR</option><option>AED</option><option>USD</option><option>GBP</option><option>EUR</option><option>SAR</option><option>QAR</option><option>OMR</option><option>BHD</option><option>ZAR</option></select></div><div class="field full"><button class="btn primary">Save profile</button></div></form>');$('#modal-close').onclick=closeModal;$('#bf').onsubmit=e=>{e.preventDefault();state.business={...state.business,...Object.fromEntries(new FormData(e.target))};save();closeModal();$('#bizName').textContent=state.business.name;go('settings');toast('Business profile updated')}}
function csv(type){const rows=state[type]||[],keys=Object.keys(rows[0]||{}),out=[keys.join(','),...rows.map(r=>keys.map(k=>'"'+String(r[k]??'').replaceAll('"','""')+'"').join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([out],{type:'text/csv'}));a.download='puravigal-'+type+'.csv';a.click();toast('CSV exported')}
const fns={dashboard,billing,products,inventory,purchases:()=>generic('purchases','Purchases','Supplier purchases and incoming stock'),customers:()=>generic('customers','Customers','Customer profiles and balances'),suppliers:()=>generic('suppliers','Suppliers','Supplier contacts and payables'),reports,team,settings};
function bind(){document.querySelectorAll('[data-go]').forEach(e=>e.onclick=()=>go(e.dataset.go));if($('#scan'))$('#scan').onclick=()=>toast('Barcode scanner ready');document.querySelectorAll('[data-add]').forEach(e=>e.onclick=()=>{const id=+e.dataset.add,x=cart.find(i=>i.id===id);if(x)x.qty++;else cart.push({id,qty:1});cartRender()});document.querySelectorAll('[data-remove]').forEach(e=>e.onclick=()=>{cart=cart.filter(i=>i.id!==+e.dataset.remove);cartRender()});document.querySelectorAll('[data-qty]').forEach(e=>e.onchange=()=>{const x=cart.find(i=>i.id===+e.dataset.qty);if(x)x.qty=Math.max(1,+e.value||1);cartRender()});if($('#bq'))$('#bq').oninput=filterBill;if($('#bc'))$('#bc').onchange=filterBill;if($('#finish'))$('#finish').onclick=finishBill;$$('.pay').forEach(b=>b.onclick=()=>{$$('.pay').forEach(x=>x.classList.remove('active'));b.classList.add('active')});if($('#pq')){$('#pq').oninput=productRows;$('#pf').onchange=productRows}if($('#add-product'))$('#add-product').onclick=()=>productForm();if($('#export-products'))$('#export-products').onclick=()=>csv('products');if($('#export-sales'))$('#export-sales').onclick=()=>csv('sales');if($('#edit-business'))$('#edit-business').onclick=businessForm;if($('#import-demo'))$('#import-demo').onclick=()=>toast('Import validation flow ready');if($('#backup'))$('#backup').onclick=()=>toast('Backup requested');if($('#invite'))$('#invite').onclick=()=>toast('Invite flow opened');if($('#quick-add'))$('#quick-add').onclick=()=>quickForm(location.hash.slice(1));document.querySelectorAll('[data-edit]').forEach(e=>e.onclick=()=>productForm(+e.dataset.edit));document.querySelectorAll('[data-perm]').forEach(e=>e.onclick=()=>toast('Permission editor opened'));document.querySelectorAll('[data-setting]').forEach(e=>e.onclick=()=>{const k=e.dataset.setting;state.settings[k]=!state.settings[k];save();render('settings')})}
function filterBill(){const q=($('#bq')?.value||'').toLowerCase(),c=$('#bc')?.value||'All categories';$('#tiles').innerHTML=tiles(state.products.filter(p=>(c==='All categories'||p.category===c)&&[p.name,p.sku].join(' ').toLowerCase().includes(q)));bind()}
function render(page){$('#app').innerHTML=(fns[page]||dashboard)();$('#title').textContent=pages[page]||'Dashboard';$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));bind();if(page==='products')productRows()}
function go(page){history.replaceState({page},'', '#'+page);render(page);$('#side').classList.remove('open');scrollTo(0,0)}
$$('#nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));$('#menu').onclick=()=>$('#side').classList.toggle('open');$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};addEventListener('popstate',()=>render(location.hash.slice(1)||'dashboard'));$('#bizName').textContent=state.business.name;render(location.hash.slice(1)||'dashboard');
Object.assign(window,{go,productForm,quickForm,businessForm,closeModal,csv,toast,filterBill});