import React,{useEffect,useMemo,useState}from"react";

const seedProducts=[{id:1,name:"Sample Product",sku:"SKU-001",barcode:"890000000001",price:100,stock:25,min:5,tax:5,category:"General"}];
const seedCustomers=[];
const seedSuppliers=[];
const modules=[
 {id:"billing",label:"Billing",icon:"₹"},{id:"products",label:"Products",icon:"▦"},{id:"inventory",label:"Inventory",icon:"◈"},
 {id:"purchases",label:"Purchases",icon:"↗"},{id:"customers",label:"Customers",icon:"◎"},{id:"suppliers",label:"Suppliers",icon:"◇"},
 {id:"reports",label:"Reports",icon:"▥"},{id:"settings",label:"Settings",icon:"⚙"}
];
const money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(Number(n||0));
function Field({label,...props}){return <label className="field"><span>{label}</span><input {...props}/></label>}
function Empty({text}){return <div className="empty"><strong>{text}</strong><small>Add your first record to get started.</small></div>}

function Billing({products,onSale}){
 const [cart,setCart]=useState([]),[q,setQ]=useState(""),[discount,setDiscount]=useState(0),[paid,setPaid]=useState(""),[method,setMethod]=useState("cash"),[customer,setCustomer]=useState("");
 const found=products.filter(p=>(p.name+" "+(p.sku||"")+" "+(p.barcode||"")).toLowerCase().includes(q.toLowerCase()));
 const subtotal=cart.reduce((s,x)=>s+x.price*x.qty,0),disc=Math.min(Number(discount)||0,subtotal),taxable=subtotal-disc,tax=cart.reduce((s,x)=>s+x.price*x.qty*(x.tax||0)/100,0)*(taxable/subtotal||0),total=Math.max(0,taxable+tax);
 const add=p=>setCart(c=>{const old=c.find(x=>x.id===p.id);return old?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]});
 const checkout=()=>{if(!cart.length)return alert("Add an item first.");if(Number(paid||total)<total)return alert("Payment is less than the bill total.");onSale({cart,subtotal,discount:disc,tax,total,paid:Number(paid||total),method,customer});setCart([]);setPaid("");setDiscount(0);};
 return <div className="pos"><div className="panel"><div className="toolbar"><div><h2>New Bill</h2><small>Fast counter billing · touch friendly</small></div><input className="searchbox" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search / barcode"/></div><div className="product-pick">{found.map(p=><button key={p.id} onClick={()=>add(p)}><strong>{p.name}</strong><small>{p.sku||"No SKU"} · {money(p.price)} · Stock {p.stock}</small></button>)}</div><div className="cart">{cart.length?cart.map(x=><div className="cart-row" key={x.id}><div><strong>{x.name}</strong><small>{money(x.price)} × {x.qty}</small></div><div className="qty"><button onClick={()=>setCart(c=>c.map(i=>i.id===x.id?{...i,qty:Math.max(1,i.qty-1)}:i))}>−</button><b>{x.qty}</b><button onClick={()=>setCart(c=>c.map(i=>i.id===x.id?{...i,qty:i.qty+1}:i))}>+</button></div><strong>{money(x.price*x.qty)}</strong></div>):<Empty text="Cart is empty"/>}</div></div><aside className="bill-summary"><h3>Bill summary</h3><Field label="Customer (optional)" value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Name / phone"/><Field label="Discount" type="number" min="0" value={discount} onChange={e=>setDiscount(e.target.value)}/><div className="totals"><span>Subtotal <b>{money(subtotal)}</b></span><span>Discount <b>-{money(disc)}</b></span><span>Tax <b>{money(tax)}</b></span><strong>Total <b>{money(total)}</b></strong></div><div className="pay-methods">{["cash","upi","card","bank","other"].map(x=><button className={method===x?"chosen":""} onClick={()=>setMethod(x)} key={x}>{x.toUpperCase()}</button>)}</div><Field label="Amount received" type="number" value={paid} onChange={e=>setPaid(e.target.value)} placeholder={String(total)}/><button className="primary wide" onClick={checkout}>Complete Sale · {money(total)}</button></aside></div>
}

function Products({products,setProducts}){
 const [form,setForm]=useState({name:"",sku:"",barcode:"",price:"",stock:"",min:"5",tax:"5",category:"General"}),[q,setQ]=useState("");
 const list=products.filter(p=>(p.name+" "+p.sku+" "+p.barcode).toLowerCase().includes(q.toLowerCase()));
 const save=e=>{e.preventDefault();if(!form.name||!form.price)return;setProducts(p=>[...p,{...form,id:Date.now(),price:Number(form.price),stock:Number(form.stock||0),min:Number(form.min||0),tax:Number(form.tax||0)}]);setForm({name:"",sku:"",barcode:"",price:"",stock:"",min:"5",tax:"5",category:"General"})};
 return <div className="module-page"><div className="page-head"><div><h2>Products</h2><p>Catalog, prices, barcode and stock settings.</p></div><input className="searchbox" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products"/></div><form className="form-card" onSubmit={save}><h3>Add product</h3><div className="form-grid"><Field label="Product name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Field label="SKU" value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/><Field label="Barcode" value={form.barcode} onChange={e=>setForm({...form,barcode:e.target.value})}/><Field label="Selling price" type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><Field label="Opening stock" type="number" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/><Field label="Minimum stock" type="number" value={form.min} onChange={e=>setForm({...form,min:e.target.value})}/><Field label="Tax %" type="number" value={form.tax} onChange={e=>setForm({...form,tax:e.target.value})}/><Field label="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></div><button className="primary">Save product</button></form><div className="table-card"><div className="table-title"><strong>{list.length} products</strong><button>Import</button><button>Export</button></div>{list.length?<div className="table">{list.map(p=><div className="tr" key={p.id}><span><strong>{p.name}</strong><small>{p.sku||"No SKU"} · {p.barcode||"No barcode"}</small></span><b>{money(p.price)}</b><span>Stock {p.stock}</span><button onClick={()=>setProducts(x=>x.filter(y=>y.id!==p.id))}>Delete</button></div>)}</div>:<Empty text="No products found"/>}</div></div>
}

function People({kind,items,setItems}){
 const [form,setForm]=useState({name:"",phone:"",email:"",tax_id:""}),[q,setQ]=useState("");
 const list=items.filter(x=>(x.name+" "+x.phone+" "+x.email).toLowerCase().includes(q.toLowerCase()));
 const save=e=>{e.preventDefault();if(!form.name)return;setItems(a=>[...a,{...form,id:Date.now()}]);setForm({name:"",phone:"",email:"",tax_id:""})};
 return <div className="module-page"><div className="page-head"><div><h2>{kind}</h2><p>{kind==="Customers"?"Profiles, history and outstanding balances.":"Supplier contacts, purchases and outstanding balances."}</p></div><input className="searchbox" value={q} onChange={e=>setQ(e.target.value)} placeholder={"Search "+kind.toLowerCase()}/></div><form className="form-card" onSubmit={save}><h3>Add {kind.slice(0,-1).toLowerCase()}</h3><div className="form-grid"><Field label="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Field label="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><Field label="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><Field label="Tax ID" value={form.tax_id} onChange={e=>setForm({...form,tax_id:e.target.value})}/></div><button className="primary">Save</button></form><div className="table-card">{list.length?list.map(x=><div className="tr" key={x.id}><span><strong>{x.name}</strong><small>{x.phone||"No phone"} · {x.email||"No email"}</small></span><span>Outstanding ₹0.00</span><button onClick={()=>setItems(a=>a.filter(y=>y.id!==x.id))}>Delete</button></div>):<Empty text={"No "+kind.toLowerCase()+" yet"}/>}</div></div>
}

function Inventory({products,setProducts,sales}){const [selected,setSelected]=useState(products[0]?.id||"");const p=products.find(x=>String(x.id)===String(selected));const [qty,setQty]=useState("");const adjust=e=>{e.preventDefault();if(!p||!qty)return;setProducts(a=>a.map(x=>x.id===p.id?{...x,stock:Math.max(0,x.stock+Number(qty))}:x));setQty("")};return <div className="module-page"><div className="page-head"><div><h2>Inventory</h2><p>Opening stock, adjustments, low-stock and movement visibility.</p></div></div><div className="stats compact"><div><span>Total items</span><strong>{products.length}</strong></div><div><span>Low stock</span><strong>{products.filter(x=>x.stock<=x.min).length}</strong></div><div><span>Out of stock</span><strong>{products.filter(x=>x.stock<=0).length}</strong></div><div><span>Sales recorded</span><strong>{sales.length}</strong></div></div><form className="form-card" onSubmit={adjust}><h3>Stock adjustment</h3><div className="form-grid"><label className="field"><span>Product</span><select value={selected} onChange={e=>setSelected(e.target.value)}>{products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><Field label="Adjustment (+ / −)" type="number" value={qty} onChange={e=>setQty(e.target.value)} placeholder="10 or -2"/></div><button className="primary">Apply adjustment</button></form><div className="table-card">{products.map(x=><div className="tr" key={x.id}><span><strong>{x.name}</strong><small>{x.sku||"No SKU"}</small></span><b>{x.stock} units</b><span className={x.stock<=x.min?"warning":""}>{x.stock<=0?"Out of stock":x.stock<=x.min?"Low stock":"Healthy"}</span></div>)}</div></div>}

function Reports({sales,products}){const total=sales.reduce((s,x)=>s+x.total,0);return <div className="module-page"><div className="page-head"><div><h2>Reports</h2><p>Business health at a glance. Filters and exports will use the same domain data.</p></div></div><div className="stats compact"><div><span>Sales</span><strong>{money(total)}</strong></div><div><span>Bills</span><strong>{sales.length}</strong></div><div><span>Products</span><strong>{products.length}</strong></div><div><span>Avg bill</span><strong>{money(sales.length?total/sales.length:0)}</strong></div></div><div className="table-card"><h3>Recent sales</h3>{sales.length?sales.slice().reverse().map(x=><div className="tr" key={x.id}><span><strong>Invoice {x.invoice}</strong><small>{x.method.toUpperCase()} · {new Date(x.createdAt).toLocaleString()}</small></span><b>{money(x.total)}</b><span>Paid {money(x.paid)}</span></div>):<Empty text="No sales yet"/>}</div></div>}

function Settings(){return <div className="module-page"><div className="page-head"><div><h2>Settings</h2><p>Business, regional, tax, users, roles and device controls.</p></div></div><div className="settings-grid">{["Business profile","Currency & timezone","Tax configuration","Users & permissions","Invoice numbering","Receipt / printer","Notifications","Security & sessions","Import / export","Subscription & limits","Backup & recovery","Audit log"].map(x=><button key={x}><strong>{x}</strong><small>Configure {x.toLowerCase()}</small><span>›</span></button>)}</div></div>}

export default function App(){
 const [active,setActive]=useState("billing"),[products,setProducts]=useState(()=>JSON.parse(localStorage.getItem("puravi_products")||"null")||seedProducts),[customers,setCustomers]=useState(seedCustomers),[suppliers,setSuppliers]=useState(seedSuppliers),[sales,setSales]=useState(()=>JSON.parse(localStorage.getItem("puravi_sales")||"[]"));
 useEffect(()=>localStorage.setItem("puravi_products",JSON.stringify(products)),[products]);useEffect(()=>localStorage.setItem("puravi_sales",JSON.stringify(sales)),[sales]);
 const today=sales.filter(x=>new Date(x.createdAt).toDateString()===new Date().toDateString()),todayTotal=today.reduce((s,x)=>s+x.total,0);
 const sale=data=>{const invoice="INV-"+String(sales.length+1).padStart(4,"0");setSales(a=>[...a,{...data,id:Date.now(),invoice,createdAt:new Date().toISOString()}]);setProducts(ps=>ps.map(p=>{const line=data.cart.find(x=>x.id===p.id);return line?{...p,stock:Math.max(0,p.stock-line.qty)}:p}));alert(invoice+" created successfully.")};
 const content=active==="billing"?<Billing products={products} onSale={sale}/>:active==="products"?<Products products={products} setProducts={setProducts}/>:active==="inventory"?<Inventory products={products} setProducts={setProducts} sales={sales}/>:active==="customers"?<People kind="Customers" items={customers} setItems={setCustomers}/>:active==="suppliers"?<People kind="Suppliers" items={suppliers} setItems={setSuppliers}/>:active==="reports"?<Reports sales={sales} products={products}/>:active==="settings"?<Settings/>:<div className="module-page"><div className="page-head"><div><h2>Purchases</h2><p>Supplier purchases and stock receiving workflow.</p></div></div><div className="empty big"><strong>Purchase workspace</strong><small>Supplier selection, purchase items, tax, payment, receiving and purchase returns are in the production API/data model and this UI is the next connected workflow.</small></div></div>;
 return <div className="app"><header className="topbar"><div className="brand"><div className="logo">P</div><div><strong>Puravigal POS</strong><span>Micro POS · Professional quality</span></div></div><div className="top-actions"><span className="online">● Local ready</span><button className="icon-button">◔</button></div></header><main><section className="welcome"><div><p className="eyebrow">PURAVIGAL POS</p><h1>{modules.find(x=>x.id===active)?.label||"Workspace"}</h1><p className="muted">Micro scope. Professional quality. Built for speed, control and reliable business data.</p></div><button className="primary" onClick={()=>setActive("billing")}>+ New Bill</button></section><section className="stats"><div><span>Today’s sales</span><strong>{money(todayTotal)}</strong><small>{today.length} bills</small></div><div><span>Products</span><strong>{products.length}</strong><small>{products.filter(x=>x.stock<=x.min).length} low stock</small></div><div><span>Customers</span><strong>{customers.length}</strong><small>Profiles</small></div><div><span>Outstanding</span><strong>₹0.00</strong><small>Needs API ledger</small></div></section><section className="workspace-shell"><aside className="sidebar"><div className="side-title">Workspace</div>{modules.map(m=><button className={active===m.id?"side-item selected":"side-item"} key={m.id} onClick={()=>setActive(m.id)}><span>{m.icon}</span>{m.label}</button>)}</aside><div className="content">{content}</div></section></main><nav className="bottom-nav">{modules.slice(0,5).map(m=><button key={m.id} className={active===m.id?"selected":""} onClick={()=>setActive(m.id)}><span>{m.icon}</span><small>{m.label}</small></button>)}</nav></div>
}